version: "3.7"

services:
  ## frontend:
  ##   build:
  ##     context: ./proj-alloc
  ##     target: "develop-stage"
  ##   ports:
  ##     - "8080:8080"
  ##   volumes:
  ##     - ".:/app"
  ##   command: /bin/sh -c "yarn serve"
  web:
    build: ./app
    image: master-image
    ports:
      - 5050:5050
    command: /usr/local/bin/gunicorn -b :5050 main:app

  worker:
    image: master-image
    depends_on:
      - redis
    command: rqworker --name worker --url redis://redis:6379/0
  # uncomment to have a another worker
  #  worker2:
  #    image: master-image
  #    depends_on:
  #      - redis
  #    command: rqworker --name worker2 --url redis://redis:6379/0

  # dashboard:
  #   image: master-image
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #   command: rq-dashboard --port 5555 --redis-url redis://redis:6379/0

  redis:
    image: redis
